### ISSUE TITLE
ソートの効率改善について

### ISSUE THREAD

**Issue by shosatojp** [MIKUEC2020/PositionStreamServer#4]
このソート部分で必要な数（100人分とか）だけ取り出すようにするともっと効率上がると思います！

https://github.com/MIKUEC2020/PositionStreamServer/blob/ea07560b50dd6bb653695f8c0c5f055597565e4d/StreamServerCommonLibrary/ExtensionMethod/HeapSort.cs#L28-L30

**Comment by shosatojp** [comment]
最も処理に時間がかかっているoutputLoopの１ループあたりにかかる時間を1000接続で測定してみました

* ソート部分：59ms
* PacketsToBuffers：12ms
* 送信部分：7ms

PacketsToBuffersのなかのPacketToBufferでunsafeのポインタ使ったり、そもそもソート以外の方法を使ったりすると高速化できそうなので試してみます

**Comment by shirakawayohane** [comment]
その部分、僕もやろうとしましたが、そもそも確かパケットがクラスだったので、
structにした場合に、リファクタリングがやや大変な作業になったのでそっ閉じしました。僕は。

**Comment by shirakawayohane** [comment]
リファクタリングさえ出来れば良いと思います！頑張ってください...!

**Comment by shosatojp** [comment]
試してみてダメだったらリファクタリングだけにしときます...

**Comment by shirakawayohane** [comment]
はい。確か一応型としてはblittableだったので、出来るならばUnsafeでブロックコピーしてしまいたかったですね...

**Comment by shosatojp** [comment]
https://github.com/MIKUEC2020/PositionStreamServer/pull/6/commits/a74711ba9ce23743241ac072c770664a3753ed8c

PacketsToBufferのところ、まだ無駄はあるものの高速化しました。C#あまり詳しくないのでとりあえず普通のunsafeだけです

BlitTableとUnsafe Classあたりのことは余裕があればやってみようと思います

**Comment by Taku3939** [comment]
ありがとうございます！！無理のない範囲でおねがいします！！

**Comment by shosatojp** [comment]
ソートの修正しました（ d7e8b40b48271fcbdc67ced98dd8495be57ff725 ）
